### ISSUE TITLE
New release timing?

### ISSUE THREAD

**Issue by BadgerOps** [quay/mirror-registry#147]
Howdy all,

I noticed the quay version was bumped to `3.8.15` yesterday, but latest quay build is `3.11.0` - I know there is some testing & all that needs to happen with the interrelated deps, and I _also_ know there are some other tasks the team is working on - but I was hoping to get a new release of mirror-registry available with a newer quay build, and the security related patches from my previous PR applied.

I happily volunteer to help test updates!

Thanks!

**Comment by HammerMeetNail** [comment]
Hey, we're actively working on getting a release out that will include your security patches, but `3.11.0` won't be released to mirror registry until we finish up the sqlite migration. It's taking a little longer than expected because we bumped into some issues related to converting an existing postgres db to a sqlite db. For reference, the reason we can't just bump to `3.11.0` is because it has a hard requirement on a newer version of Postgres that doesn't ship with mirror registry.  

Also, our QE team recently caught an [issue](https://issues.redhat.com/browse/PROJQUAY-7001) that needs further investigation before we can release with `3.8.15`. At the very least, `1.3.11` should include your security related patches. Once we sort this out, we should be able ship `1.3.11`. 

Unrelated, but thanks for all the contributions and participation. We recently started a monthly community meeting to help provide transparency and engage with the upstream community. Feel free to join next time, they are held the first Wednesday of every month 11:00 AM ET: [meeting link](https://meet.google.com/rsj-atvk-zth).

**Comment by BadgerOps** [comment]
Hey @HammerMeetNail yeah, I figured it was something along those lines - the joys of refactoring _and_ patching.

And no problem - I'm happy to contribute back, I appreciate y'all being so easy to work with. I'm in UTC +1 for the next couple months, but will try to jump in the next meetup, super excited to see that happening!

-Sol

**Comment by BadgerOps** [comment]
Oh dang @HammerMeetNail that issue you linked is my fault - I _thought_ I tested that path, but clearly missed something. I'll add a comment over there.
