### ISSUE TITLE
Latest tag for installer package from the releases page

### ISSUE THREAD

**Issue by leo8a** [quay/mirror-registry#52]
Would it be possible to have the binaries under a `latest` tag (e.g. for the online bits `https://github.com/quay/mirror-registry/releases/download/latest/mirror-registry-online.tar.gz`) as well? in that way users could get the latest bits of `mirror-registry` using the same path.

**Comment by HammerMeetNail** [comment]
@leo8a Absolutely. I just kicked off a release for the initial 1.0.0 release and it can be found at https://github.com/quay/mirror-registry/releases/latest. Please keep in mind that there's been some patches introduced since then which are available as RCs. We'll be getting a 1.1 release out in the next week or so.

**Comment by leo8a** [comment]
Thanks @HammerMeetNail! Looking forward to the 1.1 release bits next week 🙂
